# Generated by Django 2.1.7 on 2019-02-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_grid', '0003_auto_20190215_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
